####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a distroless image, tuned for Quarkus native executables.
# It greatly reduces the size of the resulting container image.
# Check https://github.com/GoogleContainerTools/distroless for further information about this image.
#
# Build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-normal-distroless -t quarkus/quarkus-test-native-distroless .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/quarkus-test-native-distroless
#
####
## Stage 1 : build with maven builder image with native capabilities
FROM quay.io/quarkus/ubi-quarkus-native-image:22.2-java17 AS stage1
USER root
RUN microdnf install findutils
COPY --chown=quarkus:quarkus gradlew /code/gradlew
COPY --chown=quarkus:quarkus gradle /code/gradle
COPY --chown=quarkus:quarkus build.gradle /code/
COPY --chown=quarkus:quarkus settings.gradle /code/
COPY --chown=quarkus:quarkus gradle.properties /code/
USER quarkus
WORKDIR /code
COPY src /code/src
RUN ./gradlew build -Dquarkus.package.type=native

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-distroless-image:1.0
WORKDIR /work/
COPY --from=stage1 /code/build/*-runner /work/application
EXPOSE 8080
USER nonroot
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
