conn = new Mongo();
db = conn.getDB("quarkusTestDB");
db.log.insertOne({"message": "Database created."});
db.createUser({
    user: 'quarkus-test-user',
    pwd: 'quarkus-test-user-password',
    roles: [{role: 'readWrite', db: 'quarkusTestDB'}],
    authenticationRestrictions: [],
    mechanisms: ["SCRAM-SHA-1", "SCRAM-SHA-256"]
});
db.movie.insertMany([
    {
        title: 'Titanic',
        year: 1997,
        genres: ['Drama', 'Romance'],
        rated: 'PG-13',
        languages: ['English', 'French', 'German', 'Swedish', 'Italian', 'Russian'],
        released: ISODate("1997-12-19T00:00:00.000Z"),
        awards: {
            wins: 127,
            nominations: 63,
            text: 'Won 11 Oscars. Another 116 wins & 63 nominations.'
        },
        cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates'],
        directors: ['James Cameron']
    },
    {
        title: 'The Dark Knight',
        year: 2008,
        genres: ['Action', 'Crime', 'Drama'],
        rated: 'PG-13',
        languages: ['English', 'Mandarin'],
        released: ISODate("2008-07-18T00:00:00.000Z"),
        awards: {
            wins: 144,
            nominations: 106,
            text: 'Won 2 Oscars. Another 142 wins & 106 nominations.'
        },
        cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
        directors: ['Christopher Nolan']
    },
    {
        title: 'Spirited Away',
        year: 2001,
        genres: ['Animation', 'Adventure', 'Family'],
        rated: 'PG',
        languages: ['Japanese'],
        released: ISODate("2003-03-28T00:00:00.000Z"),
        awards: {
            wins: 52,
            nominations: 22,
            text: 'Won 1 Oscar. Another 51 wins & 22 nominations.'
        },
        cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Takashi Naitè'],
        directors: ['Hayao Miyazaki']
    },
    {
        title: 'Casablanca',
        genres: ['Drama', 'Romance', 'War'],
        rated: 'PG',
        cast: ['Humphrey Bogart', 'Ingrid Bergman', 'Paul Henreid', 'Claude Rains'],
        languages: ['English', 'French', 'German', 'Italian'],
        released: ISODate("1943-01-23T00:00:00.000Z"),
        directors: ['Michael Curtiz'],
        awards: {
            wins: 9,
            nominations: 6,
            text: 'Won 3 Oscars. Another 6 wins & 6 nominations.'
        },
        lastupdated: '2015-09-04 00:22:54.600000000',
        year: 1942
    }
])
db.user.insertMany(
    [
        {
            "first_name": "Allie",
            "last_name": "Salan",
            "email": "asalan0@soup.io",
            "username": "asalan0"
        }, {
            "first_name": "Calhoun",
            "last_name": "Orpen",
            "email": "corpen1@mayoclinic.com",
            "username": "corpen1"
        }, {
            "first_name": "Artie",
            "last_name": "Berndsen",
            "email": "aberndsen2@abc.net.au",
            "username": "aberndsen2"
        }, {
            "first_name": "D'arcy",
            "last_name": "Roston",
            "email": "droston3@reverbnation.com",
            "username": "droston3"
        }, {
            "first_name": "Etheline",
            "last_name": "Kluge",
            "email": "ekluge4@cornell.edu",
            "username": "ekluge4"
        }, {
            "first_name": "Zea",
            "last_name": "Duinbleton",
            "email": "zduinbleton5@sakura.ne.jp",
            "username": "zduinbleton5"
        }, {
            "first_name": "Vanny",
            "last_name": "Pretorius",
            "email": "vpretorius6@4shared.com",
            "username": "vpretorius6"
        }, {
            "first_name": "Niel",
            "last_name": "Heningham",
            "email": "nheningham7@noaa.gov",
            "username": "nheningham7"
        }, {
            "first_name": "Jaquenette",
            "last_name": "Dalrymple",
            "email": "jdalrymple8@miibeian.gov.cn",
            "username": "jdalrymple8"
        }, {
            "first_name": "Hersh",
            "last_name": "Tabard",
            "email": "htabard9@paypal.com",
            "username": "htabard9"
        }, {
            "first_name": "Lisle",
            "last_name": "Sinnett",
            "email": "lsinnetta@cmu.edu",
            "username": "lsinnetta"
        }, {
            "first_name": "Michale",
            "last_name": "Shimmin",
            "email": "mshimminb@lulu.com",
            "username": "mshimminb"
        }, {
            "first_name": "Leif",
            "last_name": "Bisson",
            "email": "lbissonc@marketwatch.com",
            "username": "lbissonc"
        }, {
            "first_name": "Maren",
            "last_name": "Pottes",
            "email": "mpottesd@devhub.com",
            "username": "mpottesd"
        }, {
            "first_name": "Marcelline",
            "last_name": "Suttell",
            "email": "msuttelle@nhs.uk",
            "username": "msuttelle"
        }, {
            "first_name": "Pierrette",
            "last_name": "Carlill",
            "email": "pcarlillf@oracle.com",
            "username": "pcarlillf"
        }, {
            "first_name": "Martie",
            "last_name": "Hankins",
            "email": "mhankinsg@networksolutions.com",
            "username": "mhankinsg"
        }, {
            "first_name": "Tymothy",
            "last_name": "Lenney",
            "email": "tlenneyh@fda.gov",
            "username": "tlenneyh"
        }, {
            "first_name": "Daniele",
            "last_name": "Derges",
            "email": "ddergesi@skyrock.com",
            "username": "ddergesi"
        }, {
            "first_name": "Allyce",
            "last_name": "Kings",
            "email": "akingsj@redcross.org",
            "username": "akingsj"
        }, {
            "first_name": "Philippa",
            "last_name": "McIndoe",
            "email": "pmcindoek@tiny.cc",
            "username": "pmcindoek"
        }, {
            "first_name": "Bealle",
            "last_name": "Coolbear",
            "email": "bcoolbearl@blogtalkradio.com",
            "username": "bcoolbearl"
        }, {
            "first_name": "Christalle",
            "last_name": "Tarn",
            "email": "ctarnm@lulu.com",
            "username": "ctarnm"
        }, {
            "first_name": "Camala",
            "last_name": "Stubbins",
            "email": "cstubbinsn@reddit.com",
            "username": "cstubbinsn"
        }, {
            "first_name": "Mitch",
            "last_name": "Reason",
            "email": "mreasono@ebay.co.uk",
            "username": "mreasono"
        }, {
            "first_name": "Saw",
            "last_name": "Wardale",
            "email": "swardalep@gmpg.org",
            "username": "swardalep"
        }, {
            "first_name": "Gaylor",
            "last_name": "Lawrenz",
            "email": "glawrenzq@gravatar.com",
            "username": "glawrenzq"
        }, {
            "first_name": "Hobey",
            "last_name": "Cramp",
            "email": "hcrampr@alexa.com",
            "username": "hcrampr"
        }, {
            "first_name": "Frieda",
            "last_name": "Dory",
            "email": "fdorys@devhub.com",
            "username": "fdorys"
        }, {
            "first_name": "Fonsie",
            "last_name": "Collum",
            "email": "fcollumt@unesco.org",
            "username": "fcollumt"
        }, {
            "first_name": "Novelia",
            "last_name": "Moneypenny",
            "email": "nmoneypennyu@amazon.co.uk",
            "username": "nmoneypennyu"
        }, {
            "first_name": "Tomi",
            "last_name": "Thirst",
            "email": "tthirstv@epa.gov",
            "username": "tthirstv"
        }, {
            "first_name": "Jeni",
            "last_name": "Coldrick",
            "email": "jcoldrickw@cafepress.com",
            "username": "jcoldrickw"
        }, {
            "first_name": "Terrijo",
            "last_name": "Levinge",
            "email": "tlevingex@yahoo.com",
            "username": "tlevingex"
        }, {
            "first_name": "Rolando",
            "last_name": "Slinger",
            "email": "rslingery@wordpress.com",
            "username": "rslingery"
        }, {
            "first_name": "Palm",
            "last_name": "Mc Giffin",
            "email": "pmcgiffinz@miibeian.gov.cn",
            "username": "pmcgiffinz"
        }, {
            "first_name": "Aindrea",
            "last_name": "Barukh",
            "email": "abarukh10@constantcontact.com",
            "username": "abarukh10"
        }, {
            "first_name": "Michelina",
            "last_name": "Lemmen",
            "email": "mlemmen11@quantcast.com",
            "username": "mlemmen11"
        }, {
            "first_name": "Amandi",
            "last_name": "Davidi",
            "email": "adavidi12@naver.com",
            "username": "adavidi12"
        }, {
            "first_name": "Cilka",
            "last_name": "Bonnier",
            "email": "cbonnier13@themeforest.net",
            "username": "cbonnier13"
        }, {
            "first_name": "Isobel",
            "last_name": "Blainey",
            "email": "iblainey14@nasa.gov",
            "username": "iblainey14"
        }, {
            "first_name": "Yolanda",
            "last_name": "Blevin",
            "email": "yblevin15@ucsd.edu",
            "username": "yblevin15"
        }, {
            "first_name": "Ruthann",
            "last_name": "Wasteney",
            "email": "rwasteney16@nbcnews.com",
            "username": "rwasteney16"
        }, {
            "first_name": "Stanislaw",
            "last_name": "Macey",
            "email": "smacey17@quantcast.com",
            "username": "smacey17"
        }, {
            "first_name": "Ardath",
            "last_name": "Baumert",
            "email": "abaumert18@sbwire.com",
            "username": "abaumert18"
        }, {
            "first_name": "Michelina",
            "last_name": "Dyball",
            "email": "mdyball19@pbs.org",
            "username": "mdyball19"
        }, {
            "first_name": "Jackqueline",
            "last_name": "Davidi",
            "email": "jdavidi1a@foxnews.com",
            "username": "jdavidi1a"
        }, {
            "first_name": "Barbabra",
            "last_name": "Georgiades",
            "email": "bgeorgiades1b@auda.org.au",
            "username": "bgeorgiades1b"
        }, {
            "first_name": "Gaspar",
            "last_name": "Dispencer",
            "email": "gdispencer1c@google.de",
            "username": "gdispencer1c"
        }, {
            "first_name": "Addie",
            "last_name": "Tuckwood",
            "email": "atuckwood1d@deliciousdays.com",
            "username": "atuckwood1d"
        }, {
            "first_name": "Vinita",
            "last_name": "Kettley",
            "email": "vkettley1e@lulu.com",
            "username": "vkettley1e"
        }, {
            "first_name": "Lyndy",
            "last_name": "Glede",
            "email": "lglede1f@chronoengine.com",
            "username": "lglede1f"
        }, {
            "first_name": "Genovera",
            "last_name": "Penas",
            "email": "gpenas1g@so-net.ne.jp",
            "username": "gpenas1g"
        }, {
            "first_name": "Graehme",
            "last_name": "Legrice",
            "email": "glegrice1h@domainmarket.com",
            "username": "glegrice1h"
        }, {
            "first_name": "Ardisj",
            "last_name": "Reape",
            "email": "areape1i@nytimes.com",
            "username": "areape1i"
        }, {
            "first_name": "Eileen",
            "last_name": "McTeggart",
            "email": "emcteggart1j@princeton.edu",
            "username": "emcteggart1j"
        }, {
            "first_name": "Lorant",
            "last_name": "Shouler",
            "email": "lshouler1k@howstuffworks.com",
            "username": "lshouler1k"
        }, {
            "first_name": "Aila",
            "last_name": "Fullstone",
            "email": "afullstone1l@discovery.com",
            "username": "afullstone1l"
        }, {
            "first_name": "Loutitia",
            "last_name": "Mullord",
            "email": "lmullord1m@cdc.gov",
            "username": "lmullord1m"
        }, {
            "first_name": "Waldon",
            "last_name": "Brastead",
            "email": "wbrastead1n@360.cn",
            "username": "wbrastead1n"
        }, {
            "first_name": "Elie",
            "last_name": "Boribal",
            "email": "eboribal1o@chronoengine.com",
            "username": "eboribal1o"
        }, {
            "first_name": "Paquito",
            "last_name": "Atwool",
            "email": "patwool1p@time.com",
            "username": "patwool1p"
        }, {
            "first_name": "Lester",
            "last_name": "Brunskill",
            "email": "lbrunskill1q@mail.ru",
            "username": "lbrunskill1q"
        }, {
            "first_name": "Brande",
            "last_name": "Heppenspall",
            "email": "bheppenspall1r@mediafire.com",
            "username": "bheppenspall1r"
        }, {
            "first_name": "Lizbeth",
            "last_name": "Guichard",
            "email": "lguichard1s@parallels.com",
            "username": "lguichard1s"
        }, {
            "first_name": "Annabella",
            "last_name": "Braund",
            "email": "abraund1t@china.com.cn",
            "username": "abraund1t"
        }, {
            "first_name": "Lillis",
            "last_name": "Vasler",
            "email": "lvasler1u@intel.com",
            "username": "lvasler1u"
        }, {
            "first_name": "Ade",
            "last_name": "Herche",
            "email": "aherche1v@joomla.org",
            "username": "aherche1v"
        }, {
            "first_name": "Sybilla",
            "last_name": "Bradshaw",
            "email": "sbradshaw1w@qq.com",
            "username": "sbradshaw1w"
        }, {
            "first_name": "Brendis",
            "last_name": "Every",
            "email": "bevery1x@prweb.com",
            "username": "bevery1x"
        }, {
            "first_name": "Loleta",
            "last_name": "Risson",
            "email": "lrisson1y@sina.com.cn",
            "username": "lrisson1y"
        }, {
            "first_name": "Tammy",
            "last_name": "Cumbridge",
            "email": "tcumbridge1z@howstuffworks.com",
            "username": "tcumbridge1z"
        }, {
            "first_name": "Fleurette",
            "last_name": "Iacomettii",
            "email": "fiacomettii20@devhub.com",
            "username": "fiacomettii20"
        }, {
            "first_name": "Emylee",
            "last_name": "Lampl",
            "email": "elampl21@soup.io",
            "username": "elampl21"
        }, {
            "first_name": "Chelsy",
            "last_name": "Milburn",
            "email": "cmilburn22@livejournal.com",
            "username": "cmilburn22"
        }, {
            "first_name": "Kearney",
            "last_name": "Roselli",
            "email": "kroselli23@e-recht24.de",
            "username": "kroselli23"
        }, {
            "first_name": "Thorin",
            "last_name": "Ommanney",
            "email": "tommanney24@google.de",
            "username": "tommanney24"
        }, {
            "first_name": "Rochette",
            "last_name": "Jirasek",
            "email": "rjirasek25@pcworld.com",
            "username": "rjirasek25"
        }, {
            "first_name": "Sergei",
            "last_name": "Kettlesing",
            "email": "skettlesing26@desdev.cn",
            "username": "skettlesing26"
        }, {
            "first_name": "Dore",
            "last_name": "Dickie",
            "email": "ddickie27@dyndns.org",
            "username": "ddickie27"
        }, {
            "first_name": "Madison",
            "last_name": "Coll",
            "email": "mcoll28@sun.com",
            "username": "mcoll28"
        }, {
            "first_name": "Victoir",
            "last_name": "Carnall",
            "email": "vcarnall29@usda.gov",
            "username": "vcarnall29"
        }, {
            "first_name": "Arabel",
            "last_name": "Bulleyn",
            "email": "abulleyn2a@cbc.ca",
            "username": "abulleyn2a"
        }, {
            "first_name": "Sallie",
            "last_name": "McPhaden",
            "email": "smcphaden2b@com.com",
            "username": "smcphaden2b"
        }, {
            "first_name": "Gabi",
            "last_name": "Audry",
            "email": "gaudry2c@mapquest.com",
            "username": "gaudry2c"
        }, {
            "first_name": "Sybil",
            "last_name": "Di Antonio",
            "email": "sdiantonio2d@aboutads.info",
            "username": "sdiantonio2d"
        }, {
            "first_name": "Doralynn",
            "last_name": "Johansen",
            "email": "djohansen2e@zimbio.com",
            "username": "djohansen2e"
        }, {
            "first_name": "Angie",
            "last_name": "Lillgard",
            "email": "alillgard2f@technorati.com",
            "username": "alillgard2f"
        }, {
            "first_name": "Anissa",
            "last_name": "Legan",
            "email": "alegan2g@usda.gov",
            "username": "alegan2g"
        }, {
            "first_name": "Rowland",
            "last_name": "Threlkeld",
            "email": "rthrelkeld2h@flickr.com",
            "username": "rthrelkeld2h"
        }, {
            "first_name": "Anallise",
            "last_name": "Dunnan",
            "email": "adunnan2i@ihg.com",
            "username": "adunnan2i"
        }, {
            "first_name": "Katherine",
            "last_name": "Ellph",
            "email": "kellph2j@army.mil",
            "username": "kellph2j"
        }, {
            "first_name": "Lars",
            "last_name": "Rootham",
            "email": "lrootham2k@ebay.co.uk",
            "username": "lrootham2k"
        }, {
            "first_name": "Samantha",
            "last_name": "Makey",
            "email": "smakey2l@chicagotribune.com",
            "username": "smakey2l"
        }, {
            "first_name": "Mavis",
            "last_name": "Mouget",
            "email": "mmouget2m@angelfire.com",
            "username": "mmouget2m"
        }, {
            "first_name": "Ali",
            "last_name": "Ladds",
            "email": "aladds2n@mlb.com",
            "username": "aladds2n"
        }, {
            "first_name": "Aylmer",
            "last_name": "Ciccottini",
            "email": "aciccottini2o@noaa.gov",
            "username": "aciccottini2o"
        }, {
            "first_name": "Carmela",
            "last_name": "Bills",
            "email": "cbills2p@sun.com",
            "username": "cbills2p"
        }, {
            "first_name": "Nicolais",
            "last_name": "McNea",
            "email": "nmcnea2q@ebay.com",
            "username": "nmcnea2q"
        }, {
            "first_name": "Spike",
            "last_name": "Priver",
            "email": "spriver2r@newsvine.com",
            "username": "spriver2r"
        }
    ]
)
